### ISSUE TITLE
ise project file

### ISSUE THREAD

**Issue by vossi1** [schlae/plaid-bib-cpld#5]
Hello, I tried to build the jedec with ise 14.7 webpack.
But my jedec differs a bit from yours.
Would you please provide the complete ise project folder...

I bought a xilinx jtag programmer (jtag smt2) and just found out that impact isn't able to program the 95xx cpld's with it :(
But after some research I was able to program to a SVF-file and was able to program the cpld with the Digilent adept tool ;)
Now I only need the adept software to program the cpld's!

But it would nice to have the real ise project file.

Christian

**Comment by schlae** [comment]
I've added the .xise project file. Let me know if you still have issues.

**Comment by vossi1** [comment]
Hi, thanks for the xise file. Now I was able to compile the sources without errors.
I selected the xc9572 as target and erased+programmed to a SVF file. With digilent adept I successfully  programmed my cpld with the SVF file.
Now I have no black screen anymore - the machine boots with the plaidbib card. But it sadly is not recognized from the bios. I also tested a model 50 machine - the same.
I found a 74ALS245 and a 74F04 in an old board, desoldered and tested them in my topmax. But the same with the fast chips in the model 50 and 70 (20MHz).

PS: Is it possible to contact you with email, schlae ? I didnt found a contact possiblity at tubetime.us :(
PS2: I orders boards at jlpcb and soldered everything by myself.

I will search more tomorrow for bugs...

**Comment by schlae** [comment]
The target should be the XC9572XL which is slightly different from the plain version. Not sure if that'll make a difference but it is worth a shot.

If the BIOS doesn't recognize it, that means that the card isn't responding to the card ID command. This points to an issue with either the 74ALS245, the CPLD, the TC1262-3.3, or the 74ALS04.

* Are you sure the CPLD is soldered correctly? Check the pin 1 orientation (there is a molding mark that looks like pin 1, but it is not!) Check for solder bridges. Check for opens using a multimeter to confirm that every pin is soldered down correctly.
* Make sure the TC1262 is outputting 3.3V to the CPLD. Make sure there is not excessive ripple voltage.
* Inspect the board for bad traces. I've had that happen before due to manufacturing defects, where two adjacent traces get bridged together or sometimes broken.
* The CPLD, when misprogrammed, may have been damaged due to outputs being driven by outputs (when you noticed the black screen response). Consider swapping it out for a fresh one, but do this as a last resort.

I *highly* recommend using the xc3sprog software to program the CPLD since it can actually check for the proper responses from the device. Often SVF programmers just blindly blast the file into the JTAG port without verifying the responses.

If any of the basic stuff doesn't work, you'll need to go in with a logic analyzer (like one of those pocket USB ones) and check to see what the CPLD is doing.
* Is BUFENL# getting asserted ever?
* Is BUFDIR toggling?
* Do any of the data lines from the CPLD output any data

These kinds of problems can be hard to track down.

**Comment by vossi1** [comment]
Thanks, chip orientation is OK - looks like yours on the board ;)
3,3V is ok, I tested the TTLs in my Topmax - both ok.
The target is the XL version. The programmer recognize correctly the cpld as 9572XL.
I program with verify and got only the success message.

I will measure and check everything tomorrow.

I also have 9 other boards and some more cplds for a next try ;)

Greets

**Comment by vossi1** [comment]
I found out that my Xilinx JTAG programmer "JTAG SMT2" is nothing else than a FT232HQ in Windows 7.
I downloaded the binary xc3sprog.exe and programmed in Win7 (in OSX Parallels) the cpld.
Now my adlib card is detected, installed and sounds great with Arkanoid 2 ;)

Sadly now my harddrive adapter in my model 50 is unknown???
I removed plaid bib but its still not detected... next problem;)

Update:
In my Model 70 / 20MHz runs the plaid bib also great :)
I tested is with arkanoid2 running from OS/2 1.2 !

Next Update:
In model 50 I needed the 50-021 a special updated harddrive-ADF-file @DF9F. Now it recognizes HD and Plaidbib.
...but arkanoid doesnt find the Adlib card - so it seems that the new model 50 hd-controller is not compatible with the plaidbib. Without hd-controller booting from disk the plaidbib runs fine.

Thanks for the fantastic work - tubetime.us !!!

**Comment by schlae** [comment]
What's the exact part number of the model 70, and what planar do you have in it? I want to update the compatibility list.

**Comment by vossi1** [comment]
Hi, the following machines are ok:
8570-121 20MHz 33F6083 2x2MB 80MB HD
8570-F61 16MHz 15F8379 2x2MB 60MB HD + Adaptec AHA-1640 SCSI-Adapter

OK only without this HD-Controller: @DF9F.ADF - IBM 50-021 to 50Z HD-upgrade Controller
8550-021 10MHz 90x9161 2x512kB 60MB HD

PS: The 50z upgrade hd-controller added esdi-support (with own bios-roms) for the old full size model 50 mainboard. The new and short 50z mainboard has esdi-support integrated and the controller card is a nearly empty board!

I also tested with LS245 and LS04 TTL: The card will not be recognized in the model 70 with 20MHz!
With my 74ALS245 and the 74F04 it's fine!

**Comment by schlae** [comment]
Excellent news! I'm closing out this issue now.
